python3 << 'EOF'
content = (
    "# -*- coding: utf-8 -*-\n"
    "import asyncio\n"
    "import logging\n"
    "import gspread\n"
    "from google.oauth2.service_account import Credentials\n"
    "from datetime import date, timedelta\n"
    "from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup\n"
    "from telegram.ext import ApplicationBuilder, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes\n"
    "from apscheduler.schedulers.asyncio import AsyncIOScheduler\n\n"
    "logging.basicConfig(\n"
    "    level=logging.INFO,\n"
    "    format='%(asctime)s [%(levelname)s] %(message)s',\n"
    "    handlers=[\n"
    "        logging.FileHandler('/home/ubuntu/income_bot/bot.log'),\n"
    "        logging.StreamHandler()\n"
    "    ]\n"
    ")\n"
    "logger = logging.getLogger(__name__)\n\n"
    'TOKEN = "8650224345:AAEiS2khWhp3HcEMjvELBo8dpXELPCtiZdU"\n'
    "CHAT_ID = 8563302747\n"
    "INSURANCE = 20080\n"
    'SHEET_ID = "1im5UpkHikSwuqSZo0kuKS09yQHP9EMzLTu9_WZdtIRM"\n'
    'CREDS_FILE = "/home/ubuntu/income_bot/service_account.json"\n\n'
    "def get_sheet():\n"
    "    scopes = ['https://www.googleapis.com/auth/spreadsheets']\n"
    "    creds = Credentials.from_service_account_file(CREDS_FILE, scopes=scopes)\n"
    "    gc = gspread.authorize(creds)\n"
    "    sh = gc.open_by_key(SHEET_ID)\n"
    "    try:\n"
    "        ws = sh.worksheet('\uc218\uc785\uae30\ub85d')\n"
    "    except:\n"
    "        ws = sh.add_worksheet('\uc218\uc785\uae30\ub85d', 1000, 10)\n"
    "        ws.append_row(['\ub0a0\uc9dc', '\uc218\uc785', '\uc2dc\uc791', '\uc885\ub8cc', '\uadfc\ubb34\uc2dc\uac04', '\ubc30\ub2ec\uac74\uc218', '\uc8fc\uc720\ube44', '\ube44\uace0'])\n"
    "    return ws\n\n"
    "def save_income(date_str, amount, start_h, end_h, delivery_count, fuel_cost, memo=''):\n"
    "    try:\n"
    "        ws = get_sheet()\n"
    "        hours = end_h - start_h\n"
    "        ws.append_row([date_str, amount, start_h, end_h, hours, delivery_count, fuel_cost, memo])\n"
    "        logger.info(f'\uc800\uc7a5 \uc131\uacf5: {date_str} \uc218\uc785 {amount}\uc6d0')\n"
    "    except Exception as e:\n"
    "        logger.error(f'\uc800\uc7a5 \uc2e4\ud328: {e}')\n"
    "        raise\n\n"
    "def get_monthly_summary(date_str):\n"
    "    ws = get_sheet()\n"
    "    records = ws.get_all_records()\n"
    "    ym = date_str[:7]\n"
    "    total_a = total_h = total_d = total_f = 0\n"
    "    for r in records:\n"
    "        if str(r.get('\ub0a0\uc9dc', '')).startswith(ym):\n"
    "            total_a += int(r.get('\uc218\uc785', 0) or 0)\n"
    "            total_h += int(r.get('\uadfc\ubb34\uc2dc\uac04', 0) or 0)\n"
    "            total_d += int(r.get('\ubc30\ub2ec\uac74\uc218', 0) or 0)\n"
    "            total_f += int(r.get('\uc8fc\uc720\ube44', 0) or 0)\n"
    "    return total_a, total_h, total_d, total_f\n\n"
    "user_state = {}\n\n"
    "async def ask_income(context):\n"
    "    logger.info('13\uc2dc 30\ubd84 \uc218\uc785 \uc54c\ub9bc \ubc1c\uc1a1 \uc2dc\uc791')\n"
    "    yesterday = (date.today() - timedelta(days=1)).strftime('%Y-%m-%d')\n"
    "    await context.bot.send_message(chat_id=CHAT_ID,\n"
    "        text=f'[{yesterday}] \uc5b4\uc81c \uc218\uc785\uc740 \uc5bc\ub9c8?\\n\\n\uc608: 150000 / \ud734\ubb34: 0')\n"
    "    user_state[CHAT_ID] = {'step': 'waiting_amount', 'record_date': yesterday}\n\n"
    "async def start_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    await update.message.reply_text('[\uc218\uc785&\uc9c0\uc6b8 \uc54c\ub9bc\ubd07]\\n\\n\ub9e4\uc77c 13\uc2dc30\ubd84 \uc5b4\uc81c \uc218\uc785 \uc785\ub825\\n\uc9c0\uc6b8\uc77c D-7,D-3,\ub2f9\uc77c \uc54c\ub9bc\\n\uc6d4\ub9d0 \uacb0\uc0b0\\n\\n\uc218\ub3d9\uc785\ub825: /income\\n\ud2b9\uc815\ub0a0\uc9dc: /income 2026-05-01')\n\n"
    "async def income_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    args = context.args\n"
    "    record_date = args[0] if args else (date.today() - timedelta(days=1)).strftime('%Y-%m-%d')\n"
    "    await update.message.reply_text(f'[{record_date}] \uc5b4\uc81c \uc218\uc785\uc740 \uc5bc\ub9c8?\\n\\n\uc608: 150000 / \ud734\ubb34: 0')\n"
    "    user_state[update.effective_chat.id] = {'step': 'waiting_amount', 'record_date': record_date}\n\n"
    "async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    cid = update.effective_chat.id\n"
    "    text = update.message.text.strip()\n"
    "    state = user_state.get(cid, {})\n"
    "    if state.get('step') == 'waiting_amount':\n"
    "        try:\n"
    "            clean = text.replace(',','').replace('\uc6d0','').replace(' ','')\n"
    "            if '\ub9cc' in clean:\n"
    "                parts = clean.split('\ub9cc')\n"
    "                amount = int(parts[0]) * 10000 + (int(parts[1]) if parts[1] else 0)\n"
    "            else:\n"
    "                amount = int(clean)\n"
    "            user_state[cid]['amount'] = amount\n"
    "            user_state[cid]['step'] = 'waiting_start'\n"
    "            buttons = [\n"
    "                [InlineKeyboardButton(f'{h}\uc2dc', callback_data=f'start_{h}') for h in range(6,10)],\n"
    "                [InlineKeyboardButton(f'{h}\uc2dc', callback_data=f'start_{h}') for h in range(10,14)],\n"
    "                [InlineKeyboardButton(f'{h}\uc2dc', callback_data=f'start_{h}') for h in range(14,18)],\n"
    "                [InlineKeyboardButton(f'{h}\uc2dc', callback_data=f'start_{h}') for h in range(18,22)],\n"
    "                [InlineKeyboardButton('\ud734\ubb34 (\ubaa8\ub4e0 \uc785\ub825 \uac74\ub108\ub044\uae30)', callback_data='start_off')],\n"
    "            ]\n"
    "            await update.message.reply_text('\uadfc\ubb34 \uc2dc\uc791 \uc2dc\uac01 \uc120\ud0dd', reply_markup=InlineKeyboardMarkup(buttons))\n"
    "        except:\n"
    "            await update.message.reply_text('\uc22b\uc790\ub85c \uc785\ub825\ud574\uc8fc\uc138\uc694. \uc608: 150000')\n"
    "    elif state.get('step') == 'waiting_delivery':\n"
    "        try:\n"
    "            count = int(text.replace('\uac74','').strip())\n"
    "            user_state[cid]['delivery_count'] = count\n"
    "            user_state[cid]['step'] = 'waiting_fuel'\n"
    "            buttons = [\n"
    "                [InlineKeyboardButton('1\ub9cc\uc6d0', callback_data='fuel_10000')],\n"
    "                [InlineKeyboardButton('2\ub9cc\uc6d0', callback_data='fuel_20000')],\n"
    "                [InlineKeyboardButton('3\ub9cc\uc6d0', callback_data='fuel_30000')],\n"
    "                [InlineKeyboardButton('\uc9c1\uc811\uc785\ub825', callback_data='fuel_direct')],\n"
    "                [InlineKeyboardButton('\uc8fc\uc720 \uc548\ud568', callback_data='fuel_none')],\n"
    "            ]\n"
    "            await update.message.reply_text('\uc5b4\uc81c \uc8fc\uc720\ube44\ub294 \uc5bc\ub9c8?', reply_markup=InlineKeyboardMarkup(buttons))\n"
    "        except:\n"
    "            await update.message.reply_text('\uc22b\uc790\ub85c \uc785\ub825\ud574\uc8fc\uc138\uc694. \uc608: 50')\n"
    "    elif state.get('step') == 'waiting_fuel_direct':\n"
    "        try:\n"
    "            fuel = int(text.replace(',','').replace('\uc6d0','').strip())\n"
    "            user_state[cid]['fuel_cost'] = fuel\n"
    "            user_state[cid]['step'] = 'waiting_memo'\n"
    "            await update.message.reply_text('\ube44\uace0\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694 (\ub0a0\uc528, \uba54\ubaa8 \ub4f1)',\n"
    "                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('\uac74\ub108\ub044\uae30', callback_data='memo_skip')]]))\n"
    "        except:\n"
    "            await update.message.reply_text('\uc22b\uc790\ub85c \uc785\ub825\ud574\uc8fc\uc138\uc694. \uc608: 15000')\n"
    "    elif state.get('step') == 'waiting_memo':\n"
    "        await finish_record(update.message.reply_text, cid, state, text)\n"
    "    else:\n"
    "        await update.message.reply_text('\uc218\uc785 \uc785\ub825\uc740 /income \uc744 \ub208\ub7ec\uc8fc\uc138\uc694!')\n\n"
    "async def finish_record(reply_func, cid, state, memo):\n"
    "    amount = state['amount']\n"
    "    start_h = state.get('start_hour', 0)\n"
    "    end_h = state.get('end_hour', 0)\n"
    "    delivery_count = state.get('delivery_count', 0)\n"
    "    fuel_cost = state.get('fuel_cost', 0)\n"
    "    record_date = state['record_date']\n"
    "    save_income(record_date, amount, start_h, end_h, delivery_count, fuel_cost, memo)\n"
    "    total_a, total_h, total_d, total_f = get_monthly_summary(record_date)\n"
    "    hours = end_h - start_h\n"
    "    user_state.pop(cid, None)\n"
    "    memo_str = f'\\n\ube44\uace0: {memo}' if memo else ''\n"
    "    await reply_func(\n"
    "        f'[\uae30\ub85d\uc644\ub8cc]\\n\ub0a0\uc9dc: {record_date}\\n\uc218\uc785: {amount:,}\uc6d0\\n'\n"
    "        f'\uadfc\ubb34: {start_h}\uc2dc~{end_h}\uc2dc ({hours}\uc2dc\uac04)\\n\ubc30\ub2ec: {delivery_count}\uac74{memo_str}\\n\\n'\n"
    "        f'[{record_date[:7]} \ub204\uc801]\\n\uc218\uc785: {total_a:,}\uc6d0 / \uadfc\ubb34: {total_h}\uc2dc\uac04 / \ubc30\ub2ec: {total_d}\uac74')\n\n"
    "async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    query = update.callback_query\n"
    "    await query.answer()\n"
    "    cid = query.message.chat_id\n"
    "    data = query.data\n"
    "    state = user_state.get(cid, {})\n"
    "    if data.startswith('start_') and state.get('step') == 'waiting_start':\n"
    "        if data == 'start_off':\n"
    "            user_state[cid]['start_hour'] = 0\n"
    "            user_state[cid]['end_hour'] = 0\n"
    "            user_state[cid]['delivery_count'] = 0\n"
    "            user_state[cid]['fuel_cost'] = 0\n"
    "            record_date = state['record_date']\n"
    "            amount = state['amount']\n"
    "            save_income(record_date, amount, 0, 0, 0, 0, '\ud734\ubb34')\n"
    "            total_a, total_h, total_d, total_f = get_monthly_summary(record_date)\n"
    "            user_state.pop(cid, None)\n"
    "            await query.edit_message_text(\n"
    "                f'[\uae30\ub85d\uc644\ub8cc] \ud734\ubb34\\n\ub0a0\uc9dc: {record_date}\\n\uc218\uc785: {amount:,}\uc6d0\\n\\n'\n"
    "                f'[{record_date[:7]} \ub204\uc801]\\n\uc218\uc785: {total_a:,}\uc6d0 / \uadfc\ubb34: {total_h}\uc2dc\uac04 / \ubc30\ub2ec: {total_d}\uac74')\n"
    "        else:\n"
    "            h = int(data.split('_')[1])\n"
    "            user_state[cid]['start_hour'] = h\n"
    "            user_state[cid]['step'] = 'waiting_end'\n"
    "            buttons = []\n"
    "            row = []\n"
    "            for i in range(h+1, 25):\n"
    "                row.append(InlineKeyboardButton(f'{i}\uc2dc', callback_data=f'end_{i}'))\n"
    "                if len(row) == 4:\n"
    "                    buttons.append(row)\n"
    "                    row = []\n"
    "            if row:\n"
    "                buttons.append(row)\n"
    "            await query.edit_message_text('\uadfc\ubb34 \uc885\ub8cc \uc2dc\uac01 \uc120\ud0dd', reply_markup=InlineKeyboardMarkup(buttons))\n"
    "    elif data.startswith('end_') and state.get('step') == 'waiting_end':\n"
    "        end_h = int(data.split('_')[1])\n"
    "        user_state[cid]['end_hour'] = end_h\n"
    "        user_state[cid]['step'] = 'waiting_delivery'\n"
    "        await query.edit_message_text('\uc5b4\uc81c \ubc30\ub2ec \uac74\uc218\ub294 \uba87 \uac74? \uc22b\uc790\ub9cc \uc785\ub825\\n\uc608: 50')\n"
    "    elif data.startswith('fuel_') and state.get('step') == 'waiting_fuel':\n"
    "        if data == 'fuel_none':\n"
    "            user_state[cid]['fuel_cost'] = 0\n"
    "            user_state[cid]['step'] = 'waiting_memo'\n"
    "            await query.edit_message_text('\ube44\uace0\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694',\n"
    "                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('\uac74\ub108\ub044\uae30', callback_data='memo_skip')]]))\n"
    "        elif data == 'fuel_direct':\n"
    "            user_state[cid]['step'] = 'waiting_fuel_direct'\n"
    "            await query.edit_message_text('\uc8fc\uc720\ube44\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694\\n\uc608: 15000')\n"
    "        else:\n"
    "            fuel = int(data.replace('fuel_', ''))\n"
    "            user_state[cid]['fuel_cost'] = fuel\n"
    "            user_state[cid]['step'] = 'waiting_memo'\n"
    "            await query.edit_message_text('\ube44\uace0\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694',\n"
    "                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('\uac74\ub108\ub044\uae30', callback_data='memo_skip')]]))\n"
    "    elif data == 'memo_skip' and state.get('step') == 'waiting_memo':\n"
    "        await finish_record(query.edit_message_text, cid, state, '')\n\n"
    "async def monthly_summary(context):\n"
    "    logger.info('\uc6d4\uac04 \uacb0\uc0b0 \uc2dc\uc791')\n"
    "    yesterday = (date.today() - timedelta(days=1)).strftime('%Y-%m-%d')\n"
    "    total_a, total_h, total_d, total_f = get_monthly_summary(yesterday)\n"
    "    avg = total_a // total_h if total_h else 0\n"
    "    real_income = total_a - total_f - INSURANCE\n"
    "    await context.bot.send_message(chat_id=CHAT_ID,\n"
    "        text=f'[{yesterday[:7]} \ucd5c\uc885 \uacb0\uc0b0]\\n\\n\uc218\uc785: {total_a:,}\uc6d0\\n\uadfc\ubb34: {total_h}\uc2dc\uac04\\n\ubc30\ub2ec: {total_d}\uac74\\n\ud3c9\uade0\uc2dc\uae09: {avg:,}\uc6d0\\n\\n[\uc9c0\uc6b8]\\n\uc8fc\uc720\ube44: {total_f:,}\uc6d0\\n\ubcf4\ud5d8\ub8cc: {INSURANCE:,}\uc6d0\\n\\n\uc2e4\uc218\uc775: {real_income:,}\uc6d0')\n\n"
    "EXPENSES = [\n"
    "    (1, '\ub178\ub780\uc6b0\uc0b0\uacf5\uc81c', 50000),\n"
    "    (4, '\ubc29\uc138', 350000),\n"
    "    (10, '\ud0dc\uad8c\ub3c4\ud559\uc6d0\ube44', 240000),\n"
    "    (14, '\ub86f\ub370\uce74\ub4dc+\uc2e0\ud55c\ud6c4\ubd88\uad50\ud1b5\uce74\ub4dc', 0),\n"
    "    (17, 'K\ubc45\ud06c\ub300\ucd9c', 233000),\n"
    "    (23, '\ud55c\uad6d\uae08\uc735\uc8fc\ud0dd', 147000),\n"
    "    (26, '\ub9c1\ud0a4\uc601\uc5b4', 460000),\n"
    "]\n\n"
    "async def check_expense_alerts(context):\n"
    "    logger.info('\uc9c0\uc6b8 \uc54c\ub9bc \uccb4\ud06c \uc2dc\uc791')\n"
    "    today = date.today()\n"
    "    for day, label, amount in EXPENSES:\n"
    "        try:\n"
    "            target = today.replace(day=day)\n"
    "        except:\n"
    "            continue\n"
    "        diff = (target - today).days\n"
    "        if diff in [7, 3, 0]:\n"
    "            timing = '\uc624\ub298 \uacb0\uc81c\uc77c!' if diff==0 else f'D-{diff} ({target.month}\uc6d4{target.day}\uc77c)'\n"
    "            amt_str = f' {amount:,}\uc6d0' if amount else ''\n"
    "            await context.bot.send_message(chat_id=CHAT_ID, text=f'[\uc9c0\uc6b8\uc54c\ub9bc] {label}{amt_str}\\n{timing}')\n\n"
    "async def main():\n"
    "    app = ApplicationBuilder().token(TOKEN).build()\n"
    "    app.add_handler(CommandHandler('start', start_cmd))\n"
    "    app.add_handler(CommandHandler('income', income_cmd))\n"
    "    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))\n"
    "    app.add_handler(CallbackQueryHandler(handle_callback))\n"
    "    scheduler = AsyncIOScheduler(timezone='Asia/Seoul')\n"
    "    scheduler.add_job(ask_income, 'cron', hour=13, minute=30, args=[app])\n"
    "    scheduler.add_job(check_expense_alerts, 'cron', hour=9, minute=0, args=[app])\n"
    "    scheduler.add_job(monthly_summary, 'cron', day='1', hour=22, minute=0, args=[app])\n"
    "    scheduler.start()\n"
    "    logger.info('=== \ubd07 \uc2dc\uc791 ===')\n"
    "    await app.initialize()\n"
    "    await app.start()\n"
    "    await app.updater.start_polling()\n"
    "    await asyncio.Event().wait()\n\n"
    "if __name__ == '__main__':\n"
    "    asyncio.run(main())\n"
)
with open('/home/ubuntu/income_bot/bot.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('done')
EOF
